# Header
menu:
  Javartisan: /lee
  Java: /categories/Java
  Spring: /categories/Spring
  Mybatis: /categories/Mybatis
  Redis: /categories/Redis
  JVM: /categories/Jvm
  Spark: /categories/Spark
  Hive: /categories/Hive
  Clickhouse: /categories/Clickhouse
  Jonathan Lee: /lee
  CSDN: https://blog.csdn.net/Dax1n


#rss: /atom.xml

auto_excerpt:
  enable: true
  length: 150

# Content
excerpt_link: 点击阅读
fancybox: true





# 类目最近文章如果需要开启的打开注释
# Sidebar
sidebar: right
widgets:
- category
- archive
#
#- tag
#- tagcloud
#- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
 - category
# - tagcloud
 - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:

post_asset_folder: true
